add jenkins and elasticsearch to backup docs
portworx/pxdocs-backup pull request #38
Opened 2020-09-11 18:59 UTC by wallnerryan

- add jenkins and elasticsearch to backup docs
- Update titles for cassandra and mysql

2020-09-11 19:18 UTC, nathan-px requested changes
typos, will review again and in more detail.

2020-09-11 19:18 UTC, nathan-px commented on content/use-px-backup/backup-stateful-applications/elasticsearch.md
> +The below template can not be used alone. Please follow pre-requisits from the following [elastic on kubernetes operations guide](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.h
```suggestion
The template below can not be used alone. Please follow pre-requisites from the following [elastic on kubernetes operations guide](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html).
```

2020-09-11 19:18 UTC, nathan-px commented on content/use-px-backup/backup-stateful-applications/cassandra.md
> +title: Bacckup Cassandra on Kubernetes
```suggestion
title: Backup Cassandra on Kubernetes
```

2020-09-11 19:18 UTC, nathan-px commented on content/use-px-backup/backup-stateful-applications/elasticsearch.md
> +Before usnig this guide, make sure and configure PVCs for `elasticsearch-data`. Use the below file as an example.
```suggestion
Before using this guide, make sure and configure PVCs for `elasticsearch-data`. Use the below file as an example. 
```

2020-09-15 07:34 UTC, nathan-px requested changes

2020-09-15 07:34 UTC, nathan-px commented on content/use-px-backup/backup-stateful-applications/jenkins.md
> +Jenkins stores data within a directory known as `JENKINS_HOME`. You should configure a persistent volume for Jenkins so that the entire directory is backed by a volume to capture all data associated
same note about prerequisites as the other article.

2020-09-15 07:34 UTC, nathan-px commented on content/use-px-backup/backup-stateful-applications/jenkins.md
> +These examples assume that the Jenkins CLI is available within the Jenkins pod. You can make sure its available in the Jenkins pod(s) by running the below command.
```suggestion
**NOTE:** These examples assume that the Jenkins CLI is available within the Jenkins pod. You can make sure its available in the Jenkins pod(s) by running the below command.
```

2020-09-15 07:34 UTC, nathan-px commented on content/use-px-backup/backup-stateful-applications/jenkins.md
> +**NOTE:**
```suggestion

```

2020-09-15 07:34 UTC, nathan-px commented on content/use-px-backup/backup-stateful-applications/jenkins.md
> +Stopping a job is not necessary to backup Jenkins. It is used as an example of a pre backup rule. You may run other commands available within the Jenkins pod here as well.
```suggestion
**NOTE:** Stopping a job is not necessary to backup Jenkins. It is used as an example of a pre backup rule. You may run other commands available within the Jenkins pod here as well.
```

2020-09-15 07:34 UTC, nathan-px commented on content/use-px-backup/backup-stateful-applications/jenkins.md
> +Let's assume the Jenkins deployment has a job called `job-1`. We will use the pre-exec rule to make sure this job is stopped before taking our snapshot.
```suggestion
Assume the Jenkins deployment has a job called `job-1`, you will use the pre-exec rule to make sure this job is stopped before taking our snapshot.
```

2020-09-15 07:34 UTC, nathan-px commented on content/use-px-backup/backup-stateful-applications/jenkins.md
> +After our backup is triggered, we can start the build for `job-1` again using a post-exec rule. This ensures our job is not running during the backup and is restarted after the backup data is capture
```suggestion
After your backup is triggered, you can start the build for `job-1` again using a post-exec rule. This ensures your job is not running during the backup and is restarted after the backup data is captured. 
```

2020-09-15 13:30 UTC, wallnerryan commented on content/use-px-backup/backup-stateful-applications/elasticsearch.md
> +The template below can not be used alone. Please follow pre-requisites from the following [elastic on kubernetes operations guide](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.
ok makes sense.

2020-09-15 13:33 UTC, wallnerryan commented on content/use-px-backup/backup-stateful-applications/elasticsearch.md
> +You should first configure the Elasticsearch data directory tp use a PVC to prevent permanent data loss. Mount a Portworx volume for this purpose to `/user/share/elasticsearch/data` inside the Kubern
right. good catch. This is more of a pre-req as this applies to generally running stateful services. I'll update to identify it as a pre-req configuration of elasticsearch.

2020-09-28 15:06 UTC, wallnerryan commented
ping @nathan-px

2020-10-01 00:04 UTC, wallnerryan commented
Ping @nathan-px

2020-10-01 10:15 UTC, nathan-px commented
> Ping @nathan-px

There are still some unresolved suggestions. Do you want to proceed without those changes?

2020-10-01 13:49 UTC, wallnerryan commented
@nathan-px all suggestions should be resolved.

> > Ping @nathan-px
> 
> @wallnerryan There are still some unresolved suggestions. Do you want to proceed without those changes?

Missed those that were collapsed. Should be good now.

2020-10-02 01:41 UTC, nathan-px approved these changes

2020-10-02 03:17 UTC, merged